### ISSUE TITLE
Services shouldn't need Sync

### ISSUE THREAD

**Issue by dunmatt** [adnanademovic/rosrust#100]
I'm trying to write a service, but it's complaining that my (manually written...) ServicePair struct isn't Sync.  I can certainly go add an Arc<Mutex<, but I really shouldn't have to, the function I send in to `rosrust::service` should be given ownership of the new message, so `Send` should be sufficient.

Edit: check that, I'm getting the error because I'm trying to use a mpsc::Sender in the service function, which makes it not Sync... which is harder to solve... and equally unnecessary.  I'm giving the lambda to `service`, so again Send should be sufficient.

**Comment by adnanademovic** [comment]
Can you give me an example of how the code looks?
I'm not fully clear on what the issue is.

**Comment by dunmatt** [comment]
let (io_state_tx, io_states) = channel();
    rosrust::service("ur_driver/set_io", move |io: ur_msgs::SetIoRequest| {
        Ok(ur_msgs::SetIoResponse { success: io_state_tx.send(io).is_ok() })
    }).unwrap();

**Comment by adnanademovic** [comment]
Thanks.
I'll look into this tomorrow. You are right - I don't see any reason for that specific code not to compile.

**Comment by chachi** [comment]
I believe the where clause on the callback below is partly responsible for the Sync requirement, though it’s possible that’s necessary for the downstream threading model. 

impl Service {
    pub(crate) fn new<T, F>(
        master: Arc<Master>,
        slave: Arc<Slave>,
        hostname: &str,
        bind_address: &str,
        name: &str,
        handler: F,
    ) -> Result<Self>
    where
        T: ServicePair,
        F: Fn(T::Request) -> ServiceResult<T::Response> + Send + Sync + 'static,

**Comment by adnanademovic** [comment]
Turns out the limitation is not without a reason!
A service is able to handle more than one request at once. Thus, multiple threads should be able to call this callback at the same time.
Turns out one `mpsc::Sender` cannot be accessed from multiple threads at once, due to explicitly implementing `!Sync`.
I'd recommend using [crossbeam channels](https://docs.rs/crossbeam/0.7.1/crossbeam/channel/) for handling functionality that mpsc was handling. It has the same interface, with `Sync` implemented on senders, and with multiple receivers supported.
[This](https://github.com/adnanademovic/rosrust/blob/master/rosrust/src/tcpros/service.rs#L77-L100) is the piece of code that requires `Sync` - anything downstream does not have the `Sync` requirement anymore.
A new reference to the handler is handed to another thread for each new node that requires the service.

**Comment by dunmatt** [comment]
Ah, that makes perfect sense!  Don't know why I didn't think about concurrent requests...

Thanks for you help!
