### ISSUE TITLE
Feature Request:  A Changelog

### ISSUE THREAD

**Issue by dunmatt** [adnanademovic/rosrust#124]
Hi, I just saw that 0.9.0 had been released, and realized I have no idea what has changed and thus I don't know whether or not it's worth spending the effort to update.  Could we have a changelog?

**Comment by adnanademovic** [comment]
The API didn't change. Dependencies were upgraded, and since some of them are in the public interface, there might be a dependency version incompatibility.

It's safe to do the upgrade.

But on the actual issue - yeah, a changelog to at least summarize notable changes would have a use.

At the moment, you can look at the releases to see what changes were done.

**Comment by adnanademovic** [comment]
There is a changelog now
