### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [adnanademovic/rosrust#19]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by adnanademovic** [comment]
My xml-rpc code is the last piece of the library using it, but I'm going to switch it to serde too. That should take a couple of hours of work, and I just had other priorities.

I was waiting for [xml-rpc-rs](https://github.com/jonas-schievink/xml-rpc-rs) to develop the functionality I need, but I see that the progress on it is really slow, so I guess I'll just update my minimal implementation, rather than waiting on that.
